### 1. REGISTRAR UN NUEVO USUARIO
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "username": "usuarioDePrueba",
  "email": "prueba@gmail.com",
  "password": "123456"
}

### 2. INICIAR SESIÓN 
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "prueba@gmail.com",
  "password": "123456"
}


### 3. INICIAR SESIÓN (CONTRASEÑA INCORRECTA)
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email": "prueba@gmail.com",
  "password": "passwordINC"
}